{
 "title": "iwscan Grafana Panel",
 "description": "Example of leveraging Prometheus data from https://github.com/alepape/iwscan for WiFi monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "node", "label": "Node", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Filtered SSIDs",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "label_replace(wifi_ssids{ssid=~\"Alex.*\", instance=\"$node\"}, \"ssid\", \"n/a\", \"ssid\", \"(^$)\")",
     "legendFormat": "{{ssid}} ({{channel}})"
    }
   ]
  },
  {
   "title": "5GHz SSIDs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "label_replace(wifi_ssids{freq=~\"5.*\", instance=\"$node\"}, \"ssid\", \"n/a\", \"ssid\", \"(^$)\")",
     "legendFormat": "{{ssid}} ({{channel}})"
    }
   ]
  },
  {
   "title": "2.4GHz SSIDs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "label_replace(wifi_ssids{freq=~\"2.*\", instance=\"$node\"}, \"ssid\", \"n/a\", \"ssid\", \"(^$)\")",
     "legendFormat": "{{ssid}} ({{channel}})"
    }
   ]
  },
  {
   "title": "5GHz Channels Availability",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "avg by(channel) (wifi_ssids{freq=~\"5.*\", instance=\"$node\"})",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "2.4GHz Channels Availability",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "expr": "avg by(channel) (wifi_ssids{freq=~\"2.*\", instance=\"$node\"})",
     "legendFormat": "{{channel}}"
    }
   ]
  }
 ]
}